{# `raw` prevents jinja2 from substituting double curly braces. -#}
{% raw -%}
name: Cron Test

on:
  schedule:
  # Run every Tuesday at 10:30.
  - cron: '30 10 * * 2'

jobs:
  prerequisites:
    uses: ./.github/workflows/test.yml

{% endraw -%}
