{# `raw` prevents jinja2 from substituting double curly braces. -#}
{% raw -%}
name: CI

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  prerequisites:
    uses: ./.github/workflows/test.yml

{% endraw -%}
