{# `raw` prevents jinja2 from substituting double curly braces. -#}
{% raw -%}
name: CI-CD

on:
  push:
    branches:
    - main
    - dev
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+(a|b|rc|post|dev)[0-9]+'
  pull_request:
    branches:
    - main
    - dev

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install hatch

      - name: Check code style
        run: hatch run style:code

      - name: Check docstrings
        run: hatch run style:docstrings

      - name: Build documentation
        run: hatch run docs:build

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install hatch

    - name: Check installation
      run: hatch run install:check

    - name: Check safety
      run: hatch run safety:check

    - name: Check types
      run: hatch run types:check

    - name: Test suite
      run: hatch run +py=${{ matrix.python-version }} test:run

    - name: Report coverage
      shell: bash
      run: bash <(curl -s https://codecov.io/bash)

  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    needs: [lint, test]
    if: github.ref_type == 'tag'
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install hatch

    - name: Build package
      run: hatch build

    - name: Publish to PyPI
      env:
        HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
      run:
        hatch publish --no-prompt

    - name: GH release
      uses: softprops/action-gh-release@v2
      with:
        body: >
          Please see
          https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md
          for the full release notes.
        draft: false
        prerelease: false

{% endraw -%}
