blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: {{ cookiecutter.__dev_platform_url }}/{{cookiecutter.dev_platform_username}}/{{cookiecutter.project_slug}}/discussions
    about: Please ask and answer questions here.
